/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login_register_design;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import static login_register_design.Login_Form.current_user_username;

/**
 *
 * @author nikol
 */
public class MyWallet_Form extends javax.swing.JFrame {

    /**
     * Creates new form MyWallet_Form
     */
    public MyWallet_Form() {
        initComponents();
         this.setLocationRelativeTo(null);
         
        
         
         
        Border return_menu_border = BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(0,153,153));
        jLabel_return_menu.setBorder(return_menu_border);
        
        
        jLabel_balance.setText("BALANCE : " + Login_Form.current_user_balance+" LEVA" );
     
    }
    
    
    public boolean verifyFileds(){
        
        String balance = jTextField_deposit.getText();
      
       
       
        
        if(balance.trim().toLowerCase().equals("leva")){
            JOptionPane.showConfirmDialog(null, "One Or More Fields Are Empty","Empty Fields", 2);
            return false;
        }else return true;
    } 
    
    
    boolean verifyWithdrawMoney(){
        try{
        
        
        
        String witdraw = jTextField_withdraw.getText();
        
        
        double withdrownMoney = Double.parseDouble(jTextField_withdraw.getText());
        double balance = Login_Form.current_user_balance;
        if(balance < withdrownMoney){
            JOptionPane.showMessageDialog(null, "Error: Non-Sufficient Funds! Your Balance: " + Login_Form.current_user_balance);
            return false;  
        }else if(witdraw.trim().toLowerCase().equals("leva")){
            JOptionPane.showConfirmDialog(null, "One Or More Fields Are Empty","Empty Fields", 2);
        }
        else if(withdrownMoney < 0){
            JOptionPane.showMessageDialog(null, "Error: Sum Must Be Positive");
            return false;
        }
        
    }catch(NumberFormatException e){
                      // JOptionPane.showConfirmDialog(null, "One Or More Fields Are Empty","Empty Fields", 2);  
                }
        return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_minimize = new javax.swing.JLabel();
        jLabel_close = new javax.swing.JLabel();
        jLabel_return_menu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_minimize1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton_deposit = new javax.swing.JButton();
        jTextField_deposit = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel_balance = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jButton_withdraw = new javax.swing.JButton();
        jTextField_withdraw = new javax.swing.JTextField();

        jButton2.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jPanel3.setBackground(new java.awt.Color(0, 255, 255));

        jLabel_minimize.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_minimize.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel_minimize.setText(" -");
        jLabel_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseExited(evt);
            }
        });

        jLabel_close.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_close.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel_close.setText(" X");
        jLabel_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseExited(evt);
            }
        });

        jLabel_return_menu.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        jLabel_return_menu.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_return_menu.setText("<--  Return To Menu ");
        jLabel_return_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_return_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_return_menuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_return_menuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_return_menuMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Wallet");

        jLabel_minimize1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_minimize1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel_minimize1.setText(" -");
        jLabel_minimize1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_minimize1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimize1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_minimize1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_minimize1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_return_menu)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel_minimize1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel_minimize, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel_close)
                                .addComponent(jLabel_minimize1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel_return_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 255, 255));

        jButton_deposit.setBackground(new java.awt.Color(0, 84, 104));
        jButton_deposit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_deposit.setForeground(new java.awt.Color(255, 255, 255));
        jButton_deposit.setText("DEPOSIT");
        jButton_deposit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_depositMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_depositMouseExited(evt);
            }
        });
        jButton_deposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_depositActionPerformed(evt);
            }
        });

        jTextField_deposit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField_deposit.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_deposit.setText("LEVA");
        jTextField_deposit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_depositFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_depositFocusLost(evt);
            }
        });
        jTextField_deposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_depositActionPerformed(evt);
            }
        });
        jTextField_deposit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_depositKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jButton_deposit, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField_deposit, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(191, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_deposit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_deposit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 255, 255));

        jLabel_balance.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_balance.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_balance.setText("jLabel2");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_balance)
                .addGap(94, 94, 94))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel_balance)
                .addGap(19, 19, 19))
        );

        jPanel9.setBackground(new java.awt.Color(0, 255, 255));

        jButton_withdraw.setBackground(new java.awt.Color(0, 84, 104));
        jButton_withdraw.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_withdraw.setForeground(new java.awt.Color(255, 255, 255));
        jButton_withdraw.setText("WITHDRAW");
        jButton_withdraw.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_withdraw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_withdrawMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_withdrawMouseExited(evt);
            }
        });
        jButton_withdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_withdrawActionPerformed(evt);
            }
        });

        jTextField_withdraw.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField_withdraw.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_withdraw.setText("LEVA");
        jTextField_withdraw.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_withdrawFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_withdrawFocusLost(evt);
            }
        });
        jTextField_withdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_withdrawActionPerformed(evt);
            }
        });
        jTextField_withdraw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_withdrawKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jButton_withdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField_withdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_withdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_withdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel_minimizeMouseClicked

    private void jLabel_minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseEntered
        // TODO add your handling code here:

        jLabel_minimize.setForeground(Color.blue);
    }//GEN-LAST:event_jLabel_minimizeMouseEntered

    private void jLabel_minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseExited
        // TODO add your handling code here:

        jLabel_minimize.setForeground(Color.black);
    }//GEN-LAST:event_jLabel_minimizeMouseExited

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel_closeMouseClicked

    private void jLabel_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseEntered
        // TODO add your handling code here:

        jLabel_close.setForeground(Color.red);
    }//GEN-LAST:event_jLabel_closeMouseEntered

    private void jLabel_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseExited
        // TODO add your handling code here:

        jLabel_close.setForeground(Color.black);
    }//GEN-LAST:event_jLabel_closeMouseExited

    private void jLabel_return_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_return_menuMouseClicked
        // TODO add your handling code here:

        Menu_Form lf = new Menu_Form();
        lf.setVisible(true);
        lf.pack();
        lf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

        Menu_Form.jLabel_Welcome.setText("Hello, "+current_user_username+" what u want to do?");

    }//GEN-LAST:event_jLabel_return_menuMouseClicked

    private void jLabel_return_menuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_return_menuMouseEntered
        // TODO add your handling code here:
        Border return_menu_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.WHITE);
        jLabel_return_menu.setBorder(return_menu_border);
    }//GEN-LAST:event_jLabel_return_menuMouseEntered

    private void jLabel_return_menuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_return_menuMouseExited
        // TODO add your handling code here:
        Border return_menu_border = BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(0,153,153));
        jLabel_return_menu.setBorder(return_menu_border);

    }//GEN-LAST:event_jLabel_return_menuMouseExited

    private void jButton_depositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_depositActionPerformed
        // TODO add your handling code here:
        
      
       
        if(verifyFileds()){
            
           
            try {
                  Double deposit = Double.parseDouble(jTextField_deposit.getText());
                 PreparedStatement ps;
                     ResultSet rs;
                     String registerUserQuery = "update users set balance = balance + ? where id = ?";
                      ps = My_CNX.getConnection().prepareStatement(registerUserQuery);
                     ps.setDouble(1,deposit);
                     ps.setInt(2,Login_Form.current_user_ID);
                     if(ps.executeUpdate() != 0){
                             JOptionPane.showMessageDialog(null, "You Have To Verify The Transcation!");
                             Login_Form lf = new Login_Form();
                             lf.setVisible(true);
                             lf.pack();
                             lf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        this.dispose();
                        
                         }else{
                             JOptionPane.showMessageDialog(null, "Error : Check Your Information");
                         }
                
                
               
            } catch (SQLException ex) {
                Logger.getLogger(MyWallet_Form.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            
        }
        
        
        
    }//GEN-LAST:event_jButton_depositActionPerformed

    private void jButton_depositMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_depositMouseEntered
        // TODO add your handling code here:
        jButton_deposit.setBackground(new Color(0,84,183));
    }//GEN-LAST:event_jButton_depositMouseEntered

    private void jButton_depositMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_depositMouseExited
        // TODO add your handling code here:
         jButton_deposit.setBackground(new Color(0,84,104));
    }//GEN-LAST:event_jButton_depositMouseExited

    private void jButton_withdrawMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_withdrawMouseEntered
        // TODO add your handling code here:
        jButton_withdraw.setBackground(new Color(0,84,183));
    }//GEN-LAST:event_jButton_withdrawMouseEntered

    private void jButton_withdrawMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_withdrawMouseExited
        // TODO add your handling code here:
         jButton_withdraw.setBackground(new Color(0,84,104));
    }//GEN-LAST:event_jButton_withdrawMouseExited

    private void jTextField_withdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_withdrawActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_withdrawActionPerformed

    private void jTextField_withdrawKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_withdrawKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_withdrawKeyTyped

    private void jTextField_depositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_depositActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_depositActionPerformed

    private void jTextField_depositKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_depositKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_depositKeyTyped

    private void jTextField_depositFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_depositFocusGained
        // TODO add your handling code here:
        if(jTextField_deposit.getText().trim().equals("LEVA")){
                   jTextField_deposit.setText("");
                   jTextField_deposit.setForeground(Color.BLACK);
        }
        
    }//GEN-LAST:event_jTextField_depositFocusGained

    private void jTextField_depositFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_depositFocusLost
        // TODO add your handling code here:
        if(jTextField_deposit.getText().trim().equals("")){
              jTextField_deposit.setText("LEVA");
              jTextField_deposit.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jTextField_depositFocusLost

    private void jTextField_withdrawFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_withdrawFocusGained
        // TODO add your handling code here:
         if(jTextField_withdraw.getText().trim().equals("LEVA")){
                   jTextField_withdraw.setText("");
                   jTextField_withdraw.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextField_withdrawFocusGained

    private void jTextField_withdrawFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_withdrawFocusLost
        // TODO add your handling code here:
        if(jTextField_withdraw.getText().trim().equals("")){
              jTextField_withdraw.setText("LEVA");
               jTextField_withdraw.setForeground(new Color(153,153,153));
              
        }
    }//GEN-LAST:event_jTextField_withdrawFocusLost

    private void jLabel_minimize1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimize1MouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel_minimize1MouseClicked

    private void jLabel_minimize1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimize1MouseEntered
        // TODO add your handling code here:

        jLabel_minimize.setForeground(Color.blue);
    }//GEN-LAST:event_jLabel_minimize1MouseEntered

    private void jLabel_minimize1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimize1MouseExited
        // TODO add your handling code here:

        jLabel_minimize.setForeground(Color.black);
    }//GEN-LAST:event_jLabel_minimize1MouseExited

    private void jButton_withdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_withdrawActionPerformed
        // TODO add your handling code here:
        
        if(verifyWithdrawMoney()){
            
       
        try {
                  Double withdraw = Double.parseDouble(jTextField_withdraw.getText());
                 PreparedStatement ps;
                     ResultSet rs;
                     String registerUserQuery = "update users set balance = balance - ? where id = ?";
                      ps = My_CNX.getConnection().prepareStatement(registerUserQuery);
                     ps.setDouble(1,withdraw);
                     ps.setInt(2,Login_Form.current_user_ID);
                     if(ps.executeUpdate() != 0){
                             JOptionPane.showMessageDialog(null, "You Have To Verify The Transcation!");
                             Login_Form lf = new Login_Form();
                             lf.setVisible(true);
                             lf.pack();
                             lf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        this.dispose();
                         }else{
                             JOptionPane.showMessageDialog(null, "Error : Check Your Information");
                     }
            } catch (SQLException ex) {
                Logger.getLogger(MyWallet_Form.class.getName()).log(Level.SEVERE, null, ex);
            }catch(NumberFormatException e){
                         JOptionPane.showMessageDialog(null, "Error : Field is Empty!");
                }
         }
        
        
    }//GEN-LAST:event_jButton_withdrawActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyWallet_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyWallet_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyWallet_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyWallet_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyWallet_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_deposit;
    private javax.swing.JButton jButton_withdraw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_balance;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JLabel jLabel_minimize;
    private javax.swing.JLabel jLabel_minimize1;
    private javax.swing.JLabel jLabel_return_menu;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField_deposit;
    private javax.swing.JTextField jTextField_withdraw;
    // End of variables declaration//GEN-END:variables
}
