/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login_register_design;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.border.Border;
import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static login_register_design.Login_Form.current_user_username;
public class Products_Form extends javax.swing.JFrame {

    /**
     * Creates new form Products_Form
     */
    public Products_Form() {
        initComponents();
        this.setLocationRelativeTo(null);
        
       
       Border return_menu_border = BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(0,153,153));
        jLabel_return_menu.setBorder(return_menu_border);
        //balance
        jLabel_balance.setText("BALANCE : " + Login_Form.current_user_balance + " LEVA" );
        
        table_update();
        
 
    }
    
    private boolean buyFromMe(){
        DefaultTableModel model = (DefaultTableModel) jTable_Phones.getModel();
        int selectedRow = jTable_Phones.getSelectedRow();
        String username = jTable_Phones.getValueAt(selectedRow,6).toString();
        if(username.equals(Login_Form.current_user_usernameNotFname)){
           
            JOptionPane.showMessageDialog(null, "You Can Not Buy From Yourself!","Error",2);
            return false;
        }else{
         return true;
        }
            
                    
    }
    
    
    
    
    private void table_update(){
            
            int CC;
            
            try{
                String query ="select phone_model,price,phone_condition,phone_description,date_of_add,users.phone,users.username,phone_id  \n" +
                    "from phones\n" +
                    "join users\n" +
                    "on users.id = phones.user_id;";
                PreparedStatement ps;
                ps = My_CNX.getConnection().prepareStatement(query);
                ResultSet rs = ps.executeQuery();
                ResultSetMetaData RSMD = rs.getMetaData();
                CC = RSMD.getColumnCount();
                DefaultTableModel DFT = (DefaultTableModel) jTable_Phones.getModel();
                DFT.setRowCount(0);
                
                while(rs.next()){
                    Vector v2 = new Vector();
                    for(int ii = 1; ii <= CC; ii++){
                        v2.add(rs.getString("phone_model"));
                        v2.add(rs.getDouble("price"));
                        v2.add(rs.getString("phone_condition"));
                        v2.add(rs.getString("phone_description"));
                        v2.add(rs.getString("date_of_add"));
                        v2.add(rs.getString("users.phone"));
                        v2.add(rs.getString("users.username"));
                        v2.add(rs.getInt("phone_id"));
                        //hide the phone_id column
                        jTable_Phones.getColumnModel().getColumn(7).setMinWidth(0);
                        jTable_Phones.getColumnModel().getColumn(7).setMaxWidth(0);
                    }
                    DFT.addRow(v2);
            }
            
        }catch(Exception e){
            e.printStackTrace();
        }
            
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_minimize = new javax.swing.JLabel();
        jLabel_close = new javax.swing.JLabel();
        jLabel_return_menu = new javax.swing.JLabel();
        jLabel_balance = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Phones = new javax.swing.JTable();
        jButton_buy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jPanel3.setBackground(new java.awt.Color(0, 255, 255));

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Products");

        jLabel_minimize.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_minimize.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel_minimize.setText(" -");
        jLabel_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseExited(evt);
            }
        });

        jLabel_close.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_close.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel_close.setText(" X");
        jLabel_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseExited(evt);
            }
        });

        jLabel_return_menu.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        jLabel_return_menu.setForeground(new java.awt.Color(0, 153, 153));
        jLabel_return_menu.setText("<--  Return To Menu ");
        jLabel_return_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_return_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_return_menuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_return_menuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_return_menuMouseExited(evt);
            }
        });

        jLabel_balance.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_balance.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_balance.setText("jLabel2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel_return_menu)
                        .addGap(355, 355, 355)
                        .addComponent(jLabel1))
                    .addComponent(jLabel_balance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel_minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_close)
                    .addComponent(jLabel_return_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel_balance)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTable_Phones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Phone Model", "Price(in LEVA)", "Phone Condition", "Phone Description", "Add Date", "Contact Number", "Username", "Phone ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_Phones);

        jButton_buy.setBackground(new java.awt.Color(0, 255, 255));
        jButton_buy.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jButton_buy.setForeground(new java.awt.Color(51, 0, 102));
        jButton_buy.setText("BUY");
        jButton_buy.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_buy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_buyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_buyMouseExited(evt);
            }
        });
        jButton_buy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(482, 482, 482)
                .addComponent(jButton_buy, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_buy, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel_minimizeMouseClicked

    private void jLabel_minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseEntered
        // TODO add your handling code here:
    
        jLabel_minimize.setForeground(Color.blue);

    }//GEN-LAST:event_jLabel_minimizeMouseEntered

    private void jLabel_minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseExited
        // TODO add your handling code here:
       
        jLabel_minimize.setForeground(Color.black);
    }//GEN-LAST:event_jLabel_minimizeMouseExited

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel_closeMouseClicked

    private void jLabel_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseEntered
        // TODO add your handling code here:
        
        jLabel_close.setForeground(Color.red);

    }//GEN-LAST:event_jLabel_closeMouseEntered

    private void jLabel_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseExited
        // TODO add your handling code here:
      
        jLabel_close.setForeground(Color.black);
    }//GEN-LAST:event_jLabel_closeMouseExited

    private void jLabel_return_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_return_menuMouseClicked
        // TODO add your handling code here:

        Menu_Form lf = new Menu_Form();
        lf.setVisible(true);
        lf.pack();
        lf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        Menu_Form.jLabel_Welcome.setText("Hello, "+current_user_username+" what u want to do?");

    }//GEN-LAST:event_jLabel_return_menuMouseClicked

    private void jLabel_return_menuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_return_menuMouseEntered
        // TODO add your handling code here:
        Border return_menu_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.WHITE);
        jLabel_return_menu.setBorder(return_menu_border);
    }//GEN-LAST:event_jLabel_return_menuMouseEntered

    private void jLabel_return_menuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_return_menuMouseExited
        // TODO add your handling code here:
        Border return_menu_border = BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(0,153,153));
        jLabel_return_menu.setBorder(return_menu_border);

    }//GEN-LAST:event_jLabel_return_menuMouseExited

    private void jButton_buyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_buyMouseEntered
        // TODO add your handling code here:

        jButton_buy.setBackground(new Color(0,140,200));
    }//GEN-LAST:event_jButton_buyMouseEntered

    private void jButton_buyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_buyMouseExited
        // TODO add your handling code here:

        //set jbutton background
        jButton_buy.setBackground(new Color(0,255,255));

    }//GEN-LAST:event_jButton_buyMouseExited

    private void jButton_buyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buyActionPerformed
        // TODO add your handling code here:
try {
     String currentMoney = jTable_Phones.getValueAt(jTable_Phones.getSelectedRow(),1).toString();
      Double price = Double.valueOf(currentMoney);
      

     
      
      
        if(buyFromMe()){
                 if(Login_Form.current_user_balance < price){
                JOptionPane.showMessageDialog(null, "Error: Insufficient Funds");
            }else{
            int response = JOptionPane.showConfirmDialog(this,"Are You Sure You Want To Buy This Item?","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            if(response == JOptionPane.NO_OPTION){
//                        Products_Form form = new Products_Form();
//                        form.setVisible(true);
//                        form.pack();
//                        form.setLocationRelativeTo(null);
//                        form.dispose();
            }else if(response == JOptionPane.CLOSED_OPTION){
//                         Products_Form form = new Products_Form();
//                        form.setVisible(true);
//                        form.pack();
//                        form.setLocationRelativeTo(null);
//                        form.dispose();
            }else {
                JOptionPane.showMessageDialog(null,"You Buy The Phone Successfully!!");
        

          
            PreparedStatement ps;
            ResultSet rs;
            
            
            //String query = "DELETE FROM products WHERE product_id= ?";
            int currentId = Login_Form.current_user_ID;
            
            String currentUser = jTable_Phones.getValueAt(jTable_Phones.getSelectedRow(),6).toString();
           
            DefaultTableModel model = (DefaultTableModel) jTable_Phones.getModel();

              Connection connection = My_CNX.getConnection();
            connection.setTransactionIsolation(Connection.TRANSACTION_READ_COMMITTED);
            try{
            connection.setAutoCommit(false);
            
            // WITHDRAW
            String sqlQuery = "UPDATE users set balance = balance - ? WHERE id = ?";
            ps = connection.prepareStatement(sqlQuery); 
            
            ps.setDouble(1, price);
            ps.setInt(2,Login_Form.current_user_ID);
            ps.executeUpdate();
            
            // DEPOSIT
            String sqlQuery2 = "UPDATE users set balance = balance + ? WHERE username = ?";
             ps = connection.prepareStatement(sqlQuery2); 
             
            ps.setDouble(1, price);
            ps.setString(2,currentUser);
            ps.executeUpdate();
            
            
            connection.commit();
            
            }catch(Exception e){
            if(connection != null){
            connection.rollback();
            }
            e.printStackTrace();
            }finally{
            if(connection != null){
            connection.close();
            }
            }
            
         
            
            //DefaultTableModel model;
            model = (DefaultTableModel) jTable_Phones.getModel();
            int slectedIndex = jTable_Phones.getSelectedRow();
            
            int id = Integer.parseInt(model.getValueAt(slectedIndex,7).toString());
            
            String query = "DELETE FROM phones WHERE phone_id= ? ";
            
            ps = My_CNX.getConnection().prepareStatement(query);
            
            ps.setInt(1, id);
            ps.executeUpdate();

         
           table_update();
                  }
                 }
        }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Products_Form.class.getName()).log(Level.SEVERE, null, ex);
        }catch(ArrayIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(null,"No Phone Selected");
        }
        
      
        

    }//GEN-LAST:event_jButton_buyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Products_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Products_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Products_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Products_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Products_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_buy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_balance;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JLabel jLabel_minimize;
    private javax.swing.JLabel jLabel_return_menu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Phones;
    // End of variables declaration//GEN-END:variables
}
